### ISSUE TITLE
guide image issue #2

### ISSUE THREAD

**Issue by ghost** [samim23/DeepDreamAnim#16]
having trouble using the guide command and I always get this outcome:
```
Traceback (most recent call last):
  File "dreamer.py", line 339, in <module>
    args.zoom, args.stepsize, args.blend, args.layers, args.guide, args.gpu, args.flow)
  File "dreamer.py", line 173, in main
    guideimg = PIL.Image.open(inputdir + '/' + guide)
  File "C:\Users\root\Anaconda2\envs\caffe\lib\site-packages\PIL\Image.py", line 1952, in open
    fp = __builtin__.open(fp, "rb")
IOError: [Errno 22] invalid mode ('rb') or filename: 'C:\\Users\\root\\Desktop\\input/C:\\Users\\root\\Desktop\\input\\image-000406.png'
```

**Comment by aertist** [comment]
Use .jpg (png is not recommended)
